on:
  push:
    branches: [ '*' ]
    
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install texlive
      run: sudo apt-get install texlive texlive-latex-extra
    - uses: actions/checkout@v2
    - name: Build pdf
      run: pdflatex cv_felix_chapman.tex
    - name: Upload cv pdf
      uses: actions/upload-artifact@v2
      with:
        name: cv_pdf
        path: cv_felix_chapman.pdf

  publish:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download cv pdf
        uses: actions/download-artifact@v2
        with:
          name: cv_pdf
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Publish CV to S3
        run: aws s3 cp cv_felix_chapman.pdf s3://${{ secrets.STATIC_SITE_BUCKET }}/${{ steps.extract_branch.outputs.branch }}.pdf
